import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  background1: {
    flex: 1,
    backgroundColor: 'white',
  },
  fontanaRomaImages: {
    width: 387,
    height: 500,
    borderRadius: 22,
    alignItems: 'center',
    marginLeft: 12,
    marginTop: 11,
  },
  iconBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  iconsGroup: {
    padding: 15,
    borderRadius: 24,
    backgroundColor: '#878488',
    alignSelf: 'flex-start',
    margin: 8,
  },
  imagesBack: {
    width: 18,
    height: 17,
    alignSelf: 'center',
  },
  explainAlani: {
    padding: 10,
    height: 54,
    width: 213,
    backgroundColor: '#2D3235',
    alignSelf: 'center',
    borderRadius: 13,
    marginTop: 369,
  },
  explainTextGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textGroup: {
    fontWeight: 'bold',
    fontSize: 12,
    color: 'white',
  },
  text2Group: {
    fontWeight: '200',
    fontSize: 11,
    color: 'white',
  },
  group2: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  pinIcon: {
    width: 12,
    height: 12,
    tintColor: 'white',
    marginTop: 3,
  },
  text1Group2: {
    fontWeight: '100',
    fontSize: 12,
    color: 'white',
    marginLeft: 3,
    marginTop: 2,
  },
  textPrice: {
    fontWeight: '300',
    fontSize: 15,
    color: 'white',
    marginLeft: 93,
    marginTop: 1,
  },
  textBar2: {
    flexDirection: 'row',
    marginTop: 13,
  },
  textPopular: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginLeft: 12,
  },
  textView: {
    color: 'grey',
    fontSize: 13,
    fontWeight: '400',
    marginRight: 16,
    marginLeft: 14,
    marginTop: 3,
  },
  buttonBar: {
    flexDirection: 'row',
    gap: 65,
    justifyContent: 'flex-start',
    marginTop: 6,
    alignItems: 'flex-start',
    marginLeft: 4,
  },
  button1: {
    backgroundColor: '#EEEEEE',
    padding: 11,
    borderRadius: 7,
    marginLeft: 5,
  },
  menüBarIcons: {
    width: 15,
    height: 15,
    tintColor: 'black',
  },
  textButton1: {
    color: 'grey',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 8,
  },
  textButton2: {
    color: 'grey',
    fontSize: 15,
    fontWeight: '600',
    marginTop: 10,
  },
  buttonGroup: {
    flexDirection: 'row',
    gap: 14,
    marginLeft: 2,
    marginTop: 9,
    justifyContent: 'space-around',
    shadowColor: 'grey',
    shadowOpacity: 0.4,
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 5,
    elevation: 5,
  },
  scrollText: {
    fontSize: 13,
    fontWeight: '400',
    color: 'grey',
    marginHorizontal: 12,
  },
  buttonSon: {
    padding: 14,
    borderRadius: 21,
    backgroundColor: 'black',
    marginBottom: 24,
    marginHorizontal: 98,
    width: 234,
    shadowColor: 'grey',
    shadowOpacity: 0.4,
    shadowOffset: {width: 0, height: 4},
    shadowRadius: 5,
    elevation: 5,
  },
  buttonTextBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop:3,
  },
  buttonText1: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
   
  },
  buttonicons: {
    width: 23,
    height: 23,
    tintColor: 'white',
    alignItems: 'flex-end',
  },
});
