import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  backgrounnnf: {
    flex: 1,
    backgroundColor: 'white',
  },
  iconsBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },

  textHi: {
    color: 'Black',
    fontWeight: '500',
    fontSize: 17,
    margin: 15,
  },
  textİcon: {
    width: 23,
    height: 23,
    marginTop: 15,
  },
  iconUsers: {
    width: 32,
    height: 32,
    marginTop: 17,
    marginRight: 7,
  },
  exploreText: {
    color: 'grey',
    fontSize: 15,
    fontWeight: '300',
    marginLeft: 10,
  },
  searchAlani: {
    width: 247,
    padding: 6,
    backgroundColor: 'white',
    borderRadius: 19,
    borderColor: '#E0E0E0',
    borderWidth: 1,
    margin: 25,
    alignSelf: 'center',
  },
  searchBar: {
    flexDirection: 'row',
  },
  searchText: {
    color: '#E0E0E0',
    fontWeight: '400',
    fontSize: 12,
    textAlign: 'left',
    width: 124,
  },
  searchLine: {
    width: 5,
    padding: 2,
    backgroundColor: '#E0E0E0',
  },
  textBar2: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  textPopular: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    marginLeft: 12,
  },
  textView: {
    color: 'grey',
    fontSize: 13,
    fontWeight: '400',
    marginRight: 16,
  },
  buttonBar: {
    flexDirection: 'row',
    gap: 10,
  },
  button1: {
    padding: 15,
    borderRadius: 12,
    backgroundColor: 'black',
    width: 112,
    margin: 13,
  },
  button1Text: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
    width: 75,
    textAlign: 'center',
  },
  button2: {
    padding: 15,
    borderRadius: 12,
    backgroundColor: '#F5F5F5',
    width: 112,
    margin: 13,
  },
  button2Text: {
    color: 'grey',
    fontSize: 12,
    fontWeight: 'bold',
    width: 75,
    textAlign: 'center',
  },
  scroolImage: {
    width: 224,
    height: 345,
    borderRadius: 22,
    marginTop: 24,
    justifyContent: 'space-between',
    padding: 10,
  },
  scrollGroup: {
    padding: 17,
    borderRadius: 24,
    backgroundColor: '#878488',
    width: 10,
    alignSelf: 'flex-end',
    margin: 5,
    justifyContent: 'center',
  },
  imagesHeart: {
    width: 18,
    height: 17,
    alignSelf: 'center',
  },
  explainAlani: {
    padding: 10,
    height: 54,
    width: 168,
    backgroundColor: '#2D3235',
    alignSelf: 'center',
    borderRadius: 13,
  },
  group1: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textGroup1: {
    fontWeight: 'bold',
    fontSize: 12,
    color: 'white',
  },
  text2Group1: {
    fontWeight: '200',
    fontSize: 13,
    color: 'white',
  },
  group2: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  pinIcon: {
    width: 12,
    height: 12,
    tintColor: 'white',
    marginTop: 3,
  },
  text1Group2: {
    fontWeight: '100',
    fontSize: 12,
    color: 'white',
    marginLeft: 3,
  },
  starIcons: {
    width: 12,
    height: 12,
    tintColor: 'white',
    marginLeft: 22,
    marginTop: 3,
  },
  textStarIcon: {
    fontWeight: '300',
    fontSize: 11,
    color: 'white',
    marginLeft: 3,
    marginTop: 3,
  },
  menüBar: {
    flexDirection: 'row',
    padding:34,
    gap:65,
    alignItems:'center',
    justifyContent:'center',
  },
  menüBarIcons: {
    width: 28,
    height: 28,
    tintColor: 'grey',
  },
  menüBarHome: {
    width: 26,
    height: 28,
  },
});
